ssg: jekyll
front_matter:
  merge:
    - [categories, category]
  split:
    - categories
  flatten:
    - categories
  internals:
    - layout
    - permalink
    - published
  page:
    - categories
    - path
    - tags
    - title
