ssg: jekyll
post_name_format: (\d{4})\-(\d{2})\-(\d{2})\-(.*)\.(.*)
permalink: none
permalink_templates:
  date:    /:categories/:year/:month/:day/:title.html
  pretty:  /:categories/:year/:month/:day/:title/
  ordinal: /:categories/:year/:y_day/:title.html
  none:    /:categories/:title.html
front_matter:
  merge:
    - [categories, category]
  split:
    - categories
  flatten:
    - categories
  internals:
    - layout
    - permalink
    - published
  page:
    - categories
    - path
    - tags
    - title
